// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Temporal.MigrationTest;

namespace Temporal.MigrationTest.Migrations
{
    [DbContext(typeof(MigrationTest.TemporalTestDbContext))]
    [Migration("20210121085640_UpdateUserBecomeTemporal")]
    partial class UpdateUserBecomeTemporal
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Temporal.MigrationTest.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SysEndTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("SysEndTime")
                        .HasAnnotation("Relational:SysEndDate", true);

                    b.Property<DateTime>("SysStartTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("SysStartTime")
                        .HasAnnotation("Relational:SysStartDate", true);

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b
                        .HasAnnotation("dbo", "dbo")
                        .HasAnnotation("Relational:IsTemporal", true);
                });
#pragma warning restore 612, 618
        }
    }
}
